name: dev_blog

services:
  database:
    image: docker.io/mongo:latest
    restart: no
    volumes:
      - database-configdb:/data/configdb
      - database-db:/data/db
    ports:
      - '127.0.0.1:27017:27017'

volumes:
  database-configdb:
  database-db:
